spring.application.name=bankingsystem
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=bankingsystem
spring.datasource.hikari.connection-init-sql=CREATE SCHEMA IF NOT EXISTS bankingsystem
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cache.redis.time-to-live=900000
exchange.api.key=${70fc76a1748fc8872bec9989:}
